openapi: "3.0.0"
info:
    description: Reddit.com API
    version: 1.0.0
    title: Reddit.com
    termsOfService: https://ssl.reddit.com/dev/api
servers:
    -
        url: https://oauth.reddit.com
        description: Reddit.com API
components:
    securitySchemes:
        oauth2:
            type: oauth2
            flows:
                authorizationCode:
                    authorizationUrl: /authorize
                    tokenUrl: /access_token
                    scopes: {}
paths:
    /me:
        $ref: ./paths/me.yaml
    /user/{username}/saved:
        $ref: ./paths/saved.yaml
